version: 2

updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    commit-message:
      prefix: chore
      include: scope
    labels:
      - dependencies
    groups:
      charmbracelet:
        patterns:
          - "github.com/charmbracelet/*"
      spf13:
        patterns:
          - "github.com/spf13/*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 3
    commit-message:
      prefix: chore(ci)
    labels:
      - dependencies
      - ci
