#!/usr/bin/env bash
# bench-pr-gate.sh — invoked by the agent (or developer) before
# `gh pr create`. Runs L1, compares vs baseline, emits a Performance
# block suitable for the PR body, and decides exit code based on
# soft/hard mode AND whether a baseline existed at all.
#
# Outcomes (orthogonal to soft/hard mode):
#   clean        — compare.sh exit 0; thresholds checked, none violated
#   regression   — compare.sh exit 1; one or more rows breached threshold
#   no-baseline  — compare.sh exit 3; nothing evaluated, NEVER report ✓
#
# Mode + outcome → exit:
#   soft + any            → exit 0 (warn-only; PR opens)
#   hard + clean          → exit 0
#   hard + regression     → exit 1 (block; require --bench-skip)
#   hard + no-baseline    → exit 1 (block; force `just bench-baseline`)

. "$(dirname "$0")/lib.sh"

mode="$(bench_mode)"
machine="$(bench_machine)"

echo "═══ Performance Gate ═══"
echo "machine: $machine"
echo "mode:    $mode"
echo

# Run L1 (fastest tier; gates are L1-only by design).
"$SCRIPTS_DIR/run-l1.sh" >/dev/null

# Compare L1 vs baseline.
set +e
"$SCRIPTS_DIR/compare.sh" L1 > "$RESULTS_DIR/$machine/l1-compare.txt" 2>&1
rc=$?
set -e

cat "$RESULTS_DIR/$machine/l1-compare.txt"

# Map compare.sh exit code to a single status used in the PR body. The
# explicit no-baseline status is the load-bearing distinction Codex
# flagged: a missing baseline must NOT look like a clean run.
case "$rc" in
    0)  status_line="✓ within L1 thresholds" ;;
    1)  status_line="✗ L1 regression detected" ;;
    3)  status_line="⚠ no baseline for machine \`$machine\` — gate NOT evaluated" ;;
    *)  status_line="✗ compare.sh failed (exit=$rc)" ;;
esac

# PR-body block: machine-readable section the agent embeds verbatim
# under `## Performance` in the PR body.
{
    echo
    echo "## Performance"
    echo
    echo "<!-- generated by bench/scripts/bench-pr-gate.sh — do not edit -->"
    echo "- machine: \`$machine\`"
    echo "- mode: \`$mode\`"
    echo "- status: $status_line"
    echo
    echo '```text'
    cat "$RESULTS_DIR/$machine/l1-compare.txt"
    echo '```'
} > "$RESULTS_DIR/$machine/pr-block.md"

echo
echo "→ PR body block written to: $RESULTS_DIR/$machine/pr-block.md"
echo "  Agent: paste verbatim into the PR body under ## Performance"

# Hard mode: ANY non-clean compare.sh result blocks. We list the
# specific cases inline so the failure message is actionable, but
# unknown rc values (e.g. compare.sh internal error, benchstat
# install failure, awk script crash) MUST also block — silently
# passing on those defeats the whole point of the mandatory gate.
if [ "$mode" = "hard" ] && [ "$rc" -ne 0 ]; then
    echo
    case "$rc" in
        1)
            days_active=$(( ($(date +%s) - $(cat "$GATE_FILE" 2>/dev/null || echo $(date +%s))) / 86400 ))
            echo "BLOCKED: hard gate active (${days_active}d since activation)"
            echo "         resolve regression OR pass --bench-skip with justification"
            ;;
        3)
            echo "BLOCKED: no baseline for machine '$machine' — gate cannot evaluate."
            echo "         record one: just bench-baseline l1"
            echo "         then commit bench/baseline/$machine and retry."
            ;;
        *)
            echo "BLOCKED: compare.sh failed unexpectedly (exit=$rc)."
            echo "         see $RESULTS_DIR/$machine/l1-compare.txt for details."
            echo "         hard gate cannot accept silent pass on unknown failures."
            ;;
    esac
    exit 1
fi

# Soft mode warnings (do not block, just surface the issue).
if [ "$rc" -eq 1 ]; then
    echo
    echo "WARN: regression visible. Soft mode — not blocking."
    if [ -s "$GATE_FILE" ]; then
        days_left=$(( ($(cat "$GATE_FILE") + 14*86400 - $(date +%s)) / 86400 ))
        echo "      hard gate activates in ~${days_left}d"
    else
        echo "      gate not activated yet (run: just bench-gate-activate)"
    fi
elif [ "$rc" -eq 3 ]; then
    echo
    echo "WARN: no baseline for machine '$machine' — gate not evaluated."
    echo "      record one with: just bench-baseline l1"
    echo "      and commit bench/baseline/$machine to make the gate meaningful."
fi

exit 0
